// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Metzenas

//@version=4
study("MC - Defensive", overlay=true)

n1 = input(10, "Channel Length")
n2 = input(21, "Average Length")
ema21 = input(21, "EMA 21")
obLevel1 = input(60, "Over Bought Level 1")
obLevel2 = input(53, "Over Bought Level 2")
osLevel1 = input(-60, "Over Sold Level 1")
osLevel2 = input(-53, "Over Sold Level 2")

ap = hlc3 
esa = ema(ap, n1)
d = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ema(ci, n2)
ema21_ = ema(hlc3, ema21)
 
wt1 = tci
wt2 = sma(wt1,3)
crossCondition = cross(wt1, wt2)
long_condition = (wt2 - wt1 <= 0)
short_condition = (wt2 - wt1 > 0)


// Money Flow
length = input(title="Length", type=input.integer, defval=60, minval=1, maxval=2000)
src = hlc3
upper = sum(volume * (change(src) <= 0 ? 0 : src), length)
lower = sum(volume * (change(src) >= 0 ? 0 : src), length)
_rsi(upper, lower) =>
    if lower == 0
        100
    if upper == 0
        0
	100.0 - (100.0 / (1.0 + upper / lower))
mf = _rsi(upper, lower)

// Filters
body_size = abs(close - open) / (high - low)

// Base conditions
long_0 = wt2 <= 0 and mf <= 40
short_0 = wt2 >= 40 and mf >= 55

// Base
long_signal_base = crossCondition and (wt2 - wt1 <= 0) and long_0
short_signal_base = crossCondition and (wt2 - wt1 > 0) and short_0 and body_size >= 0.2

alertcondition(long_signal_base, "MC open", "MC - Buy")
alertcondition(short_signal_base, "MC close", "MC - Sell")

if (long_signal_base)
    l = label.new(bar_index, high)
    label.set_text(l, "buy_base@\n"+tostring(close))
    label.set_color(l, color.green)
    label.set_yloc(l, yloc.price)
    label.set_style(l, label.style_labelup)
    
if (short_signal_base)
    l = label.new(bar_index, high)
    label.set_text(l, "sell_base@\n"+tostring(close))
    label.set_color(l, color.red)
    label.set_yloc(l, yloc.price)
    label.set_style(l, label.style_labeldown)
