// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © Metzenas

//@version=2
study("MC Study", overlay=true)

n1 = input(10, "Channel Length")
n2 = input(21, "Average Length")
obLevel1 = input(60, "Over Bought Level 1")
obLevel2 = input(53, "Over Bought Level 2")
osLevel1 = input(-60, "Over Sold Level 1")
osLevel2 = input(-53, "Over Sold Level 2")

ap = hlc3 
esa = ema(ap, n1)
d = ema(abs(ap - esa), n1)
ci = (ap - esa) / (0.015 * d)
tci = ema(ci, n2)
 
wt1 = tci
wt2 = sma(wt1,3)
crossCondition = cross(wt1, wt2)


// Money Flow
length = input(title="Length", type=input.integer, defval=60, minval=1, maxval=2000)
src = hlc3
upper = sum(volume * (change(src) <= 0 ? 0 : src), length)
lower = sum(volume * (change(src) >= 0 ? 0 : src), length)
_rsi(upper, lower) =>
    if lower == 0
        100
    if upper == 0
        0
	100.0 - (100.0 / (1.0 + upper / lower))
mf = _rsi(upper, lower)

longSignal = crossCondition and (wt2 - wt1 <= 0) and wt2 <= 40 and wt1 <= 40 and mf <= 40 
shortSignal = crossCondition and (wt2 - wt1 > 0) and wt2 >= 40 and wt2 >= 40 and mf >= 60 

alertcondition(longSignal, "MC long open", "message")
alertcondition(shortSignal, "MC long close", "message")

if (longSignal)
    l = label.new(bar_index, high)
    label.set_text(l, "buy@\n"+tostring(close))
    label.set_color(l, color.green)
    label.set_yloc(l, yloc.belowbar)
    label.set_style(l, label.style_labelup)
    
if (shortSignal)
    l = label.new(bar_index, high)
    label.set_text(l, "sell@\n"+tostring(close))
    label.set_color(l, color.red)
    label.set_yloc(l, yloc.abovebar)
    label.set_style(l, label.style_labeldown)
